-- 외부 LLM 전송에 대한 사용자 동의 기록.
--
-- 시각만 남기지 않고 동의한 정책 버전을 함께 남긴다. 외부 LLM 제공자나 보관 정책이 바뀌면
-- 새 버전으로 재동의를 받아야 하는데, 시각만 있으면 "무엇에 동의했는지"를 알 수 없어
-- 재동의 대상을 고를 수 없다. 현재 버전은 설정값(galpi.consent.ai-data-version)이다.
--
-- 이전 버전의 동의 행은 지우지 않는다. 동의 이력 자체가 근거이고, 연결을 해제하거나
-- 재동의를 받아도 과거에 무엇에 동의했는지는 남아 있어야 한다.
CREATE TABLE ai_data_consents
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL,
    consent_version VARCHAR(20) NOT NULL,
    agreed_at       TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ,
    CONSTRAINT fk_ai_data_consents_user FOREIGN KEY (user_id) REFERENCES users (id),
    -- 같은 버전에 두 번 동의해도 행은 하나다. 동의 버튼 중복 클릭이 이력을 부풀리지 않는다.
    CONSTRAINT uk_ai_data_consents_user_version UNIQUE (user_id, consent_version)
);

-- 분석 실행마다 "이 사용자가 현재 버전에 동의했는가"를 묻는다.
CREATE INDEX idx_ai_data_consents_user ON ai_data_consents (user_id);
