-- Phase 1F PR 요약.
--
-- 수집(1C)은 PR을 DB에 넣고 끝났다. 그것을 읽는 화면이 요구하는 것은 "이 PR이 무엇을 했는지"
-- 한 문장인데, 그 문장을 만들려면 diff가 필요하고 diff는 §5.4에 따라 어디에도 저장하지
-- 않는다. 그래서 요약은 수집과 같은 트랜잭션이 아니라 별도 워커가 맡고, 워커는 요약 직전에
-- GitHub에서 patch를 다시 받아 메모리에서 LLM으로만 보낸다.
--
-- 그 구조 때문에 이 테이블은 결과 테이블인 동시에 큐다. 별도 큐 테이블을 만들지 않는다 --
-- 상태·시도 횟수·선점 필드를 결과와 같은 행에 두면 analysis_runs가 쓰는
-- SELECT ... FOR UPDATE SKIP LOCKED 패턴을 그대로 쓸 수 있고, 화면의 "실패한 PR만 다시
-- 분석"이 새 행을 만드는 일이 아니라 status를 되돌리는 UPDATE 한 번이 된다.
CREATE TABLE pull_request_analyses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT      NOT NULL,
    -- 요약을 만들려면 patch를 GitHub에서 다시 받아야 하고, 워커에는 사용자 세션이 없다.
    -- 인계 시점에 검증된 installation을 여기 저장한다. analysis_run_repositories와 같은
    -- 이유이고, repositories.installation_id를 쓰지 않는 이유이기도 하다 -- 저쪽은 주석이
    -- "캐시"라고 못박은 값이라 인계 근거로 쓸 수 없다. 같은 head를 재수집해도 App 재설치가
    -- 반영되도록 최신 검증값으로 갱신한다.
    installation_id BIGINT      NOT NULL,
    -- 동의를 다시 확인할 대상. 워커가 프로젝트 소유자를 거슬러 올라가지 않아도 되게 둔다.
    requested_by    BIGINT      NOT NULL,
    status          VARCHAR(20) NOT NULL,
    -- 어느 커밋 기준의 요약인지. PR이 다시 수집돼 head_sha가 바뀌면 요약은 낡은 것이 되고,
    -- 인계 쪽이 그 사실을 이 값의 비교만으로 판단해 PENDING으로 되돌린다.
    head_sha        VARCHAR(40) NOT NULL,

    -- 아래 셋은 COMPLETED일 때만 채운다.
    summary         TEXT,
    change_type     VARCHAR(30),
    model           VARCHAR(100),

    -- FAILED나 CANCELLED일 때 채운다. spec_documents.failure_code와 같은 규칙이다. 사용자에게 나가는
    -- ErrorCode와는 별개의 값이다 -- 이쪽은 화면이 "왜 분석하지 못했는지"를 설명하는 데 쓰고,
    -- HTTP 상태로 번역되지 않는다.
    error_code      VARCHAR(50),
    error_message   TEXT,

    claimed_by      VARCHAR(100),
    claimed_at      TIMESTAMPTZ,
    -- rate limit처럼 정해진 시각 전에는 다시 시도할 의미가 없는 경우 사용한다. PENDING이어도
    -- 이 시각이 미래면 선점 대상이 아니다.
    next_attempt_at TIMESTAMPTZ,
    attempts        INT         NOT NULL DEFAULT 0,
    analyzed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ,

    CONSTRAINT fk_pull_request_analyses_pull_request
        FOREIGN KEY (pull_request_id) REFERENCES pull_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_pull_request_analyses_user
        FOREIGN KEY (requested_by) REFERENCES users (id),
    -- PR 하나에 요약은 하나다. 재요약은 새 행이 아니라 이 행의 갱신이다.
    CONSTRAINT uk_pull_request_analyses_pull_request UNIQUE (pull_request_id),
    CONSTRAINT ck_pull_request_analyses_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    -- 상태와 채워진 값이 어긋나면 화면이 "성공인데 요약이 없는" 행을 그린다. DB에서 막는다.
    CONSTRAINT ck_pull_request_analyses_completed
        CHECK ((status = 'COMPLETED') = (summary IS NOT NULL AND change_type IS NOT NULL)),
    CONSTRAINT ck_pull_request_analyses_terminal_reason
        CHECK ((status IN ('FAILED', 'CANCELLED')) = (error_code IS NOT NULL)),
    CONSTRAINT ck_pull_request_analyses_change_type
        CHECK (change_type IS NULL OR change_type IN
               ('FEATURE', 'BUGFIX', 'REFACTOR', 'TEST', 'DOCS',
                'INFRA', 'STYLE', 'REVERT', 'CHORE', 'OTHER'))
);

-- 워커 선점 쿼리가 탄다.
--
-- 부분 인덱스인 것이 중요하다. 요약이 한 바퀴 끝나면 사실상 모든 행이 COMPLETED가 되므로,
-- 조건 없이 만들면 선점 쿼리에 영영 쓰이지 않을 항목이 인덱스의 99%를 차지한다. 선점은
-- PENDING과 lease가 지난 RUNNING만 보므로 그 둘만 담는다.
--
-- 600,000행(COMPLETED) 중 PENDING 300건을 고르는 선점 쿼리를 실측했을 때 0.53ms였다.
CREATE INDEX idx_pull_request_analyses_claimable
    ON pull_request_analyses (status, next_attempt_at, claimed_at)
    WHERE status IN ('PENDING', 'RUNNING');

-- 목록·집계 조회를 위한 인덱스는 만들지 않는다.
--
-- 목록은 프로젝트 단위인데 pull_requests에는 project_id가 없어 repositories를 조인해야 하고,
-- 정렬 기본이 merged_at DESC라 저장소가 여럿이면 여러 인덱스 구간을 합쳐야 한다. 그래서
-- 인덱스가 더 필요해 보이지만, 실제 실행 계획은 그렇지 않았다.
--
--   60,000행 (프로젝트 50 x 저장소 4 x PR 300)
--     -> Seq Scan on pull_requests + Hash Join. 11.1ms.
--        기존 idx_pull_requests_repository_merged_at을 쓰지 않는다. 저장소 4행과의
--        hash join이 실제로 더 싸기 때문이고, 그 판단이 맞다.
--   600,000행 (10배)
--     -> Bitmap Index Scan on idx_pull_requests_repository_merged_at (loops=4). 13.7ms.
--        플래너가 스스로 갈아탄다.
--
-- 즉 작을 때는 seq scan이 더 싸고 커지면 이미 있는 인덱스가 받는다. 이 쿼리에 부족한
-- 인덱스는 없다.
--
-- 정렬 자체를 없애려면 pull_requests에 project_id를 비정규화하고 (project_id, merged_at DESC)를
-- 걸어야 하는데, 저장소 3~5개 x PR 수백 건에서 11ms를 없애자고 수집 경로에 컬럼을 하나 더
-- 다는 것은 값어치가 없다. 규모가 그보다 훨씬 커지면 그때 다시 잰다.
