-- 기능대조 실행/PR별 큐/다대다 연결. 사용자 연결은 실행과 독립적으로 유지한다.
CREATE TABLE feature_match_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
 spec_document_id BIGINT NOT NULL REFERENCES spec_documents(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id),
 status VARCHAR(30) NOT NULL CHECK(status IN ('QUEUED','RUNNING','COMPLETED','PARTIALLY_COMPLETED','FAILED','CANCELLED')),
 feature_snapshot_hash VARCHAR(64) NOT NULL,
 feature_count INT NOT NULL CHECK(feature_count > 0),
 eligible_pr_count INT NOT NULL CHECK(eligible_pr_count > 0),
 excluded_failed_pr_count INT NOT NULL DEFAULT 0,
 excluded_cancelled_pr_count INT NOT NULL DEFAULT 0,
 failure_code VARCHAR(50),
 started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_feature_match_runs_active ON feature_match_runs(project_id)
 WHERE status IN ('QUEUED','RUNNING');
CREATE INDEX idx_feature_match_runs_project ON feature_match_runs(project_id,id DESC);

CREATE TABLE feature_match_targets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 feature_match_run_id BIGINT NOT NULL REFERENCES feature_match_runs(id) ON DELETE CASCADE,
 pull_request_analysis_id BIGINT NOT NULL REFERENCES pull_request_analyses(id) ON DELETE CASCADE,
 analysis_head_sha VARCHAR(40) NOT NULL,
 analysis_snapshot_hash VARCHAR(64) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')),
 claimed_by VARCHAR(100), claimed_at TIMESTAMPTZ, next_attempt_at TIMESTAMPTZ,
 attempts INT NOT NULL DEFAULT 0, failure_code VARCHAR(50),
 started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
 UNIQUE(feature_match_run_id,pull_request_analysis_id),
 UNIQUE(id,feature_match_run_id)
);
CREATE INDEX idx_feature_match_targets_queue ON feature_match_targets(status,next_attempt_at,claimed_at)
 WHERE status IN ('PENDING','RUNNING');
CREATE TABLE feature_pr_matches (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 feature_match_run_id BIGINT REFERENCES feature_match_runs(id) ON DELETE CASCADE,
 feature_match_target_id BIGINT,
 feature_id BIGINT NOT NULL REFERENCES features(id) ON DELETE CASCADE,
 pull_request_id BIGINT NOT NULL REFERENCES pull_requests(id) ON DELETE CASCADE,
 source VARCHAR(10) NOT NULL CHECK(source IN ('AI','USER')),
 reason TEXT, user_id BIGINT REFERENCES users(id),
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
 FOREIGN KEY(feature_match_target_id,feature_match_run_id) REFERENCES feature_match_targets(id,feature_match_run_id) ON DELETE CASCADE,
 CHECK((source='AI' AND feature_match_run_id IS NOT NULL AND feature_match_target_id IS NOT NULL AND reason IS NOT NULL AND user_id IS NULL)
    OR (source='USER' AND feature_match_run_id IS NULL AND feature_match_target_id IS NULL AND reason IS NULL AND user_id IS NOT NULL))
);
CREATE UNIQUE INDEX uk_feature_pr_matches_ai ON feature_pr_matches(feature_match_run_id,feature_id,pull_request_id) WHERE source='AI';
CREATE UNIQUE INDEX uk_feature_pr_matches_user ON feature_pr_matches(feature_id,pull_request_id) WHERE source='USER';
CREATE INDEX idx_feature_pr_matches_feature ON feature_pr_matches(feature_id);
CREATE INDEX idx_feature_pr_matches_pr ON feature_pr_matches(pull_request_id);
CREATE TABLE feature_pr_match_requirements (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 feature_pr_match_id BIGINT NOT NULL REFERENCES feature_pr_matches(id) ON DELETE CASCADE,
 feature_requirement_id BIGINT NOT NULL REFERENCES feature_requirements(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
 UNIQUE(feature_pr_match_id,feature_requirement_id)
);
CREATE INDEX idx_feature_pr_match_requirements_requirement ON feature_pr_match_requirements(feature_requirement_id);
