CREATE TABLE users
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id                BIGINT      NOT NULL,
    login                    VARCHAR(39) NOT NULL,
    name                     VARCHAR(255),
    email                    VARCHAR(255),
    avatar_url               VARCHAR(500),
    role                     VARCHAR(20) NOT NULL DEFAULT 'USER',
    github_connection_status VARCHAR(20) NOT NULL DEFAULT 'CONNECTED',
    connected_at             TIMESTAMPTZ NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ,
    CONSTRAINT uk_users_github_id UNIQUE (github_id),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_github_connection_status
        CHECK (github_connection_status IN ('CONNECTED', 'DISCONNECTED'))
);

CREATE INDEX idx_users_login ON users (login);

CREATE TABLE user_oauth_tokens
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT      NOT NULL,
    provider                VARCHAR(20) NOT NULL DEFAULT 'GITHUB',
    encrypted_access_token  TEXT        NOT NULL,
    access_token_expires_at TIMESTAMPTZ,
    token_version           INT         NOT NULL DEFAULT 1,
    issued_at               TIMESTAMPTZ NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ,
    CONSTRAINT fk_user_oauth_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_user_oauth_tokens_user_provider UNIQUE (user_id, provider),
    CONSTRAINT ck_user_oauth_tokens_provider CHECK (provider IN ('GITHUB'))
);
