-- GitHub에 폐기를 요청하지 못한 user access token의 재시도 큐.
-- 연결 해제는 GitHub 장애로 막히지 않아야 하지만, 로컬 원본만 지우면 외부에 살아 있는
-- 토큰을 회수할 수 없으므로 암호문을 여기 남겨 두고 배치가 재시도한다.
CREATE TABLE github_token_revocations
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT      NOT NULL,
    encrypted_access_token TEXT        NOT NULL,
    token_version          INT         NOT NULL DEFAULT 1,
    attempts               INT         NOT NULL DEFAULT 1,
    next_attempt_at        TIMESTAMPTZ NOT NULL,
    last_error             VARCHAR(100),
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ
);

-- 배치가 매번 스캔하는 조건.
CREATE INDEX idx_github_token_revocations_due
    ON github_token_revocations (next_attempt_at, attempts);
