-- projects는 ERD에 있지만 아직 마이그레이션이 없었다. repositories가 여기에 매달리므로
-- 저장소 연결(1B)을 넣으려면 먼저 만들어야 한다. 컬럼은 기존 코드가 쓰던 것과 같게 두고
-- 새로 늘리지 않는다. 프로젝트 자체의 기능은 이 마이그레이션의 범위가 아니다.
CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_projects_user ON projects (user_id);

-- 프로젝트에 실제로 연결된 저장소만 들어간다. 사용자가 고를 수 있는 저장소 전체 목록은
-- 여기 미러링하지 않는다 — 그 목록은 매번 GitHub에 실시간으로 묻는다.
--
-- github_repository_id가 관계의 유일한 영속 키다. installation_id는 캐시고, owner·name·
-- full_name은 표시용 스냅샷이라 GitHub에서 이름이 바뀌면 목록 조회 때 갱신된다.
-- 이 세 값으로 저장소를 식별하면 이름 변경 한 번에 연결이 끊기므로 관계 판단에 쓰지 않는다.
CREATE TABLE repositories
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id           BIGINT       NOT NULL,
    github_repository_id BIGINT       NOT NULL,
    installation_id      BIGINT,
    owner                VARCHAR(100) NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    full_name            VARCHAR(200) NOT NULL,
    private              BOOLEAN      NOT NULL,
    default_branch       VARCHAR(255) NOT NULL,
    html_url             VARCHAR(500) NOT NULL,
    access_status        VARCHAR(20)  NOT NULL DEFAULT 'ACCESSIBLE',
    last_synced_at       TIMESTAMPTZ,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT fk_repositories_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT uk_repositories_project_github_repository
        UNIQUE (project_id, github_repository_id),
    CONSTRAINT ck_repositories_access_status
        CHECK (access_status IN ('ACCESSIBLE', 'INACCESSIBLE'))
);

-- 같은 GitHub 저장소가 여러 프로젝트에 걸쳐 있을 때 한 번에 찾기 위한 인덱스.
CREATE INDEX idx_repositories_github_repository_id ON repositories (github_repository_id);
