-- 기능명세서 분석 결과 데이터 모델.

CREATE TABLE projects
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_projects_user ON projects (user_id);

CREATE TABLE spec_documents
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    user_id           BIGINT       NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    extraction_status VARCHAR(20)  NOT NULL,
    failure_code      VARCHAR(30),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_spec_documents_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_spec_documents_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_spec_documents_extraction_status
        CHECK (extraction_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_spec_documents_failure_code
        CHECK (failure_code IN ('NO_FEATURE_EXTRACTED', 'ANALYSIS_FAILED')),
    CONSTRAINT ck_spec_documents_failure_code_only_when_failed
        CHECK (failure_code IS NULL OR extraction_status = 'FAILED')
);

CREATE INDEX idx_spec_documents_project ON spec_documents (project_id);

CREATE TABLE feature_sections
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_document_id BIGINT       NOT NULL,
    title            VARCHAR(255) NOT NULL,
    source_title     TEXT,
    display_order    INT          NOT NULL,
    page_start       INT,
    page_end         INT,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ,
    CONSTRAINT fk_feature_sections_spec_document
        FOREIGN KEY (spec_document_id) REFERENCES spec_documents (id) ON DELETE CASCADE
);

CREATE INDEX idx_feature_sections_spec_document ON feature_sections (spec_document_id);

CREATE TABLE features
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_document_id  BIGINT       NOT NULL,
    section_id        BIGINT,
    name              VARCHAR(255) NOT NULL,
    display_order     INT          NOT NULL,
    source_page_start INT,
    source_page_end   INT,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_features_spec_document
        FOREIGN KEY (spec_document_id) REFERENCES spec_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_features_section
        FOREIGN KEY (section_id) REFERENCES feature_sections (id) ON DELETE SET NULL
);

CREATE INDEX idx_features_spec_document ON features (spec_document_id);
CREATE INDEX idx_features_section ON features (section_id);

CREATE TABLE feature_requirements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id    BIGINT      NOT NULL,
    content       TEXT        NOT NULL,
    source_text   TEXT        NOT NULL,
    display_order INT         NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT fk_feature_requirements_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);

CREATE INDEX idx_feature_requirements_feature ON feature_requirements (feature_id);

CREATE TABLE feature_issues
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id  BIGINT      NOT NULL,
    issue_type  VARCHAR(30) NOT NULL,
    description TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT fk_feature_issues_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT ck_feature_issues_issue_type
        CHECK (issue_type IN ('DUPLICATE_SUSPECTED', 'MISSING_REQUIREMENTS', 'SPLIT_RECOMMENDED',
                              'SOURCE_REVIEW_REQUIRED', 'SOURCE_CONTENT_CONFLICT'))
);

CREATE INDEX idx_feature_issues_feature ON feature_issues (feature_id);

CREATE TABLE duplicate_candidates
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id            BIGINT      NOT NULL,
    target_feature_id     BIGINT      NOT NULL,
    reason                TEXT         NOT NULL,
    suggested_merged_name VARCHAR(255) NOT NULL,
    suggested_section     VARCHAR(255) NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT fk_duplicate_candidates_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT fk_duplicate_candidates_target_feature
        FOREIGN KEY (target_feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT uk_duplicate_candidates_pair UNIQUE (feature_id, target_feature_id),
    CONSTRAINT ck_duplicate_candidates_not_self CHECK (feature_id <> target_feature_id)
);

CREATE INDEX idx_duplicate_candidates_target_feature ON duplicate_candidates (target_feature_id);

CREATE TABLE split_feature_suggestions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id        BIGINT       NOT NULL,
    suggested_name    VARCHAR(255) NOT NULL,
    suggested_section VARCHAR(255) NOT NULL,
    display_order     INT          NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_split_feature_suggestions_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);

CREATE INDEX idx_split_feature_suggestions_feature ON split_feature_suggestions (feature_id);

CREATE TABLE split_suggestion_requirements
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_feature_suggestion_id BIGINT      NOT NULL,
    feature_requirement_id      BIGINT      NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL,
    updated_at                  TIMESTAMPTZ,
    CONSTRAINT fk_split_suggestion_requirements_suggestion
        FOREIGN KEY (split_feature_suggestion_id) REFERENCES split_feature_suggestions (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_split_suggestion_requirements_requirement
        FOREIGN KEY (feature_requirement_id) REFERENCES feature_requirements (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_split_suggestion_requirements_pair
        UNIQUE (split_feature_suggestion_id, feature_requirement_id)
);

CREATE INDEX idx_split_suggestion_requirements_requirement
    ON split_suggestion_requirements (feature_requirement_id);
