-- 기능명세서 분석 결과 데이터 모델.
--
-- projects와 spec_documents는 엔티티만 있고 마이그레이션이 없어 ddl-auto=validate가 통과하지
-- 못하는 상태였다. 분석 테이블들이 spec_documents를 참조해야 하므로 여기서 함께 만든다.
-- 두 테이블의 컬럼 정의는 현재 엔티티 매핑을 그대로 옮긴 것이다 — projects가 created_at과
-- updated_at을 갖지 않는 것도 Project만 BaseEntity를 상속하지 않는 현재 코드를 따른 결과다.

CREATE TABLE projects
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_projects_user ON projects (user_id);

CREATE TABLE spec_documents
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    user_id           BIGINT       NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    extraction_status VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_spec_documents_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_spec_documents_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_spec_documents_extraction_status
        CHECK (extraction_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_spec_documents_project ON spec_documents (project_id);

-- 아래 분석 결과 테이블들은 문서를 지우면 남아 있을 이유가 없다. 계층이 다섯 단계라
-- 애플리케이션이 삭제 순서를 직접 챙기면 언젠가 순서를 틀려 FK 위반이 나므로 DB에 맡긴다.

CREATE TABLE feature_sections
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_document_id BIGINT       NOT NULL,
    -- title은 서비스가 쓰는 정리된 이름, source_title은 PDF에 실제로 적혀 있던 제목.
    -- 원문에 없던 분류를 의미상 새로 묶으면 source_title과 페이지 범위가 비어 있다.
    title            VARCHAR(255) NOT NULL,
    source_title     VARCHAR(255),
    display_order    INT          NOT NULL,
    page_start       INT,
    page_end         INT,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ,
    CONSTRAINT fk_feature_sections_spec_document
        FOREIGN KEY (spec_document_id) REFERENCES spec_documents (id) ON DELETE CASCADE
);

CREATE INDEX idx_feature_sections_spec_document ON feature_sections (spec_document_id);

CREATE TABLE features
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_document_id  BIGINT       NOT NULL,
    -- 어느 분류에도 들어가지 않는 기능이 있을 수 있어 비워 둘 수 있다. 분류가 사라져도
    -- 기능까지 사라지면 안 되므로 여기만 CASCADE가 아니라 SET NULL이다.
    section_id        BIGINT,
    name              VARCHAR(255) NOT NULL,
    display_order     INT          NOT NULL,
    source_page_start INT,
    source_page_end   INT,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_features_spec_document
        FOREIGN KEY (spec_document_id) REFERENCES spec_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_features_section
        FOREIGN KEY (section_id) REFERENCES feature_sections (id) ON DELETE SET NULL
);

CREATE INDEX idx_features_spec_document ON features (spec_document_id);
CREATE INDEX idx_features_section ON features (section_id);

CREATE TABLE feature_requirements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id    BIGINT      NOT NULL,
    -- content는 정리된 문장, source_text는 그 근거가 된 원문. 요구사항은 원문에서 뽑아낸
    -- 것이므로 근거 없는 요구사항은 성립하지 않는다. 길이는 통제할 수 없어 상한을 두지 않는다.
    content       TEXT        NOT NULL,
    source_text   TEXT        NOT NULL,
    display_order INT         NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT fk_feature_requirements_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);

CREATE INDEX idx_feature_requirements_feature ON feature_requirements (feature_id);

-- 한 기능이 여러 문제를 동시에 가질 수 있어 (feature_id, issue_type)에 unique를 걸지 않는다.
CREATE TABLE feature_issues
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id  BIGINT      NOT NULL,
    issue_type  VARCHAR(30) NOT NULL,
    description TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT fk_feature_issues_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT ck_feature_issues_issue_type
        CHECK (issue_type IN ('DUPLICATE_SUSPECTED', 'MISSING_REQUIREMENTS', 'SPLIT_RECOMMENDED',
                              'SOURCE_REVIEW_REQUIRED', 'SOURCE_CONTENT_CONFLICT'))
);

CREATE INDEX idx_feature_issues_feature ON feature_issues (feature_id);

-- 두 FK가 모두 features를 가리킨다. feature가 중복으로 지목된 쪽, target_feature가 합칠 상대다.
-- 방향에 의미가 있어 id 순서로 정규화하지 않으므로, (A→B)와 (B→A)가 함께 들어오는 대칭 중복은
-- 행 하나로 판단할 수 없어 DB가 막지 못한다 — 결과를 저장하는 쪽의 몫이다.
--
-- suggested_section은 FK가 아니다. 제안 시점에 그 분류가 아직 feature_sections에 없을 수 있는데,
-- FK로 두면 사용자가 승인하지도 않은 분류를 미리 만들어야 한다.
CREATE TABLE duplicate_candidates
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id            BIGINT      NOT NULL,
    target_feature_id     BIGINT      NOT NULL,
    reason                TEXT         NOT NULL,
    suggested_merged_name VARCHAR(255) NOT NULL,
    suggested_section     VARCHAR(255) NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT fk_duplicate_candidates_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT fk_duplicate_candidates_target_feature
        FOREIGN KEY (target_feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT uk_duplicate_candidates_pair UNIQUE (feature_id, target_feature_id),
    CONSTRAINT ck_duplicate_candidates_not_self CHECK (feature_id <> target_feature_id)
);

-- feature_id는 위 unique 인덱스의 선두 컬럼이라 따로 만들지 않는다. 반대쪽은 커버되지 않아
-- 역방향 조회와 features 삭제 시 FK 검사가 전부 full scan이 되므로 인덱스가 필요하다.
CREATE INDEX idx_duplicate_candidates_target_feature ON duplicate_candidates (target_feature_id);

-- 아직 실제 기능이 아니라 사용자가 분리를 적용하기 전의 제안이므로 features에 행을 만들지 않는다.
CREATE TABLE split_feature_suggestions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id        BIGINT       NOT NULL,
    suggested_name    VARCHAR(255) NOT NULL,
    suggested_section VARCHAR(255) NOT NULL,
    display_order     INT          NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_split_feature_suggestions_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);

CREATE INDEX idx_split_feature_suggestions_feature ON split_feature_suggestions (feature_id);

-- 분리 제안에 기존 요구사항을 배정한 연결. 제안 하나가 요구사항 여럿을 가져가고 요구사항
-- 하나가 여러 제안에 등장할 수도 있어 다대다다.
--
-- 테이블명이 엔티티명(SplitSuggestionFeatureRequirement)보다 짧다. 그대로 옮기면 제약 이름이
-- PostgreSQL의 식별자 한계(63바이트)에 걸리는데, 넘긴 이름은 경고 없이 잘려 나가 충돌한다.
CREATE TABLE split_suggestion_requirements
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_feature_suggestion_id BIGINT      NOT NULL,
    feature_requirement_id      BIGINT      NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL,
    updated_at                  TIMESTAMPTZ,
    CONSTRAINT fk_split_suggestion_requirements_suggestion
        FOREIGN KEY (split_feature_suggestion_id) REFERENCES split_feature_suggestions (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_split_suggestion_requirements_requirement
        FOREIGN KEY (feature_requirement_id) REFERENCES feature_requirements (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_split_suggestion_requirements_pair
        UNIQUE (split_feature_suggestion_id, feature_requirement_id)
);

CREATE INDEX idx_split_suggestion_requirements_requirement
    ON split_suggestion_requirements (feature_requirement_id);
