-- 기능명세서 업로드(featurespec)의 SpecDocument 엔티티에 대응하는 테이블.
--
-- 엔티티는 main에 들어왔는데 마이그레이션이 없어 ddl-auto=validate가 부팅을 거부했다.
-- 스키마를 만드는 것은 Hibernate가 아니라 Flyway이므로, 엔티티를 추가하면 여기도 함께
-- 추가해야 한다. 이 어긋남을 잡으라고 통합 테스트가 validate로 도는 것이다.
--
-- project_id는 V3의 projects를 참조한다. 이 테이블도 그 마이그레이션이 없으면 만들어지지
-- 않으므로, featurespec은 V3보다 뒤에 와야 한다.
CREATE TABLE spec_documents
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    user_id           BIGINT       NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    extraction_status VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_spec_documents_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_spec_documents_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 한 프로젝트의 명세서를 모아 보는 것이 기본 조회 경로다.
CREATE INDEX idx_spec_documents_project ON spec_documents (project_id);

-- ExtractionStatus에 지금은 PENDING뿐이지만 상태가 늘어날 예정이라, 값을 열거하는 CHECK는
-- 넣지 않는다. 넣으면 enum 상수를 추가할 때마다 마이그레이션이 하나씩 더 필요해진다.
-- V3의 access_status는 두 값이 고정이라 CHECK를 걸었다 — 같은 규칙을 기계적으로 적용하지 마라.
