-- Phase 1C 데이터 수집 모델.
--
-- 스키마 문서는 analysis_runs를 "컬럼 추가"로 적었지만 실제로는 테이블 자체가 없다.
-- ERD에만 있고 마이그레이션이 없던 상태라 여기서 CREATE로 만든다.
--
-- 코드 원문은 어느 테이블에도 들어가지 않는다. pull_request_files에 patch 컬럼이 없는 것이
-- 그 정책의 핵심이고, 경로·변경량·생략 여부만 남는다.

-- PR 작성자. 갈피 회원이 아닐 수 있어 users와 별도다. 프로젝트 단위로 모으는 이유는
-- 같은 GitHub 계정이라도 프로젝트마다 기여 맥락이 다르기 때문이다.
CREATE TABLE contributors
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT      NOT NULL,
    github_user_id BIGINT      NOT NULL,
    login          VARCHAR(39) NOT NULL,
    avatar_url     VARCHAR(500),
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ,
    CONSTRAINT fk_contributors_project FOREIGN KEY (project_id) REFERENCES projects (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_contributors_project_github_user UNIQUE (project_id, github_user_id)
);

-- 병합된 PR만 들어온다. merged_at이 NOT NULL인 것이 그 수집 범위를 스키마로 못박은 것이다.
--
-- contributor_id가 NULL을 허용하는 이유는 GitHub 계정이 삭제되면 PR 응답의 user가 null로
-- 오기 때문이다. 그 PR을 버리면 기능 구현 근거가 사라지므로 작성자만 비우고 수집한다.
--
-- body는 코드 원문이 아니라 저장하지만, 사용자가 자격증명을 붙여넣을 수 있어 저장 전에
-- 마스킹을 거친다.
CREATE TABLE pull_requests
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id          BIGINT       NOT NULL,
    contributor_id         BIGINT,
    github_pull_request_id BIGINT       NOT NULL,
    number                 INT          NOT NULL,
    title                  VARCHAR(500) NOT NULL,
    body                   TEXT,
    base_ref               VARCHAR(255) NOT NULL,
    head_ref               VARCHAR(255) NOT NULL,
    base_sha               VARCHAR(40)  NOT NULL,
    head_sha               VARCHAR(40)  NOT NULL,
    merge_commit_sha       VARCHAR(40),
    merged_at              TIMESTAMPTZ  NOT NULL,
    created_at_github      TIMESTAMPTZ  NOT NULL,
    changed_files_count    INT          NOT NULL DEFAULT 0,
    additions              INT          NOT NULL DEFAULT 0,
    deletions              INT          NOT NULL DEFAULT 0,
    html_url               VARCHAR(500) NOT NULL,
    data_completeness      VARCHAR(20)  NOT NULL DEFAULT 'COMPLETE',
    incomplete_reasons     JSONB,
    collected_at           TIMESTAMPTZ  NOT NULL,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ,
    CONSTRAINT fk_pull_requests_repository FOREIGN KEY (repository_id) REFERENCES repositories (id)
        ON DELETE CASCADE,
    -- 작성자 행이 사라져도 PR은 남아야 한다. 근거로 쓰이는 쪽은 PR이다.
    CONSTRAINT fk_pull_requests_contributor FOREIGN KEY (contributor_id) REFERENCES contributors (id)
        ON DELETE SET NULL,
    CONSTRAINT uk_pull_requests_repository_number UNIQUE (repository_id, number),
    CONSTRAINT ck_pull_requests_data_completeness
        CHECK (data_completeness IN ('COMPLETE', 'PARTIAL'))
);

CREATE INDEX idx_pull_requests_repository_merged_at
    ON pull_requests (repository_id, merged_at DESC);

-- patch 컬럼이 없는 것이 의도다. diff 원문은 수집 시점에 메모리에서 분석 파이프라인으로만
-- 넘어가고 여기 남지 않는다. patch_omitted는 GitHub이 큰 파일·바이너리의 patch를 생략했다는
-- 사실만 기록한다.
CREATE TABLE pull_request_files
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT        NOT NULL,
    path            VARCHAR(1000) NOT NULL,
    previous_path   VARCHAR(1000),
    change_status   VARCHAR(20)   NOT NULL,
    additions       INT           NOT NULL DEFAULT 0,
    deletions       INT           NOT NULL DEFAULT 0,
    changes         INT           NOT NULL DEFAULT 0,
    patch_omitted   BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ   NOT NULL,
    updated_at      TIMESTAMPTZ,
    CONSTRAINT fk_pull_request_files_pull_request
        FOREIGN KEY (pull_request_id) REFERENCES pull_requests (id) ON DELETE CASCADE,
    CONSTRAINT uk_pull_request_files_pull_request_path UNIQUE (pull_request_id, path),
    CONSTRAINT ck_pull_request_files_change_status
        CHECK (change_status IN ('ADDED', 'MODIFIED', 'REMOVED', 'RENAMED', 'COPIED'))
);

-- 커밋 메시지에도 마스킹을 적용한 값이 들어온다.
CREATE TABLE pull_request_commits
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id  BIGINT      NOT NULL,
    sha              VARCHAR(40) NOT NULL,
    message          TEXT        NOT NULL,
    author_login     VARCHAR(39),
    author_github_id BIGINT,
    authored_at      TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ,
    CONSTRAINT fk_pull_request_commits_pull_request
        FOREIGN KEY (pull_request_id) REFERENCES pull_requests (id) ON DELETE CASCADE,
    CONSTRAINT uk_pull_request_commits_pull_request_sha UNIQUE (pull_request_id, sha)
);

-- 분석 대상에서만 빼고 수집은 유지한다. 되돌릴 수 있어야 하므로 물리 삭제하지 않는다.
CREATE TABLE pr_exclusions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT      NOT NULL,
    excluded_by     BIGINT      NOT NULL,
    reason          VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ,
    CONSTRAINT fk_pr_exclusions_pull_request
        FOREIGN KEY (pull_request_id) REFERENCES pull_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_pr_exclusions_user FOREIGN KEY (excluded_by) REFERENCES users (id),
    CONSTRAINT uk_pr_exclusions_pull_request UNIQUE (pull_request_id)
);

-- repository_id가 NULL이면 프로젝트 기본값이다.
CREATE TABLE analysis_configs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT      NOT NULL,
    repository_id BIGINT,
    pr_limit      INT         NOT NULL DEFAULT 300,
    pr_since      TIMESTAMPTZ,
    include_paths JSONB,
    exclude_paths JSONB,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT fk_analysis_configs_project FOREIGN KEY (project_id) REFERENCES projects (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_analysis_configs_repository FOREIGN KEY (repository_id) REFERENCES repositories (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_analysis_configs_project_repository UNIQUE (project_id, repository_id),
    CONSTRAINT ck_analysis_configs_pr_limit CHECK (pr_limit > 0)
);

-- 위 UNIQUE는 repository_id가 NULL인 행들을 서로 다른 값으로 봐서 프로젝트 기본값이 여러 개
-- 생기는 것을 막지 못한다. 기본값은 하나여야 하므로 부분 인덱스로 따로 막는다.
CREATE UNIQUE INDEX uk_analysis_configs_project_default
    ON analysis_configs (project_id) WHERE repository_id IS NULL;

-- installation_snapshot이 이 테이블의 핵심이다. 작업을 만드는 시점(사용자 세션이 있을 때)에
-- 권한을 재검증하며 만든 githubRepositoryId -> installationId 매핑을 여기 고정한다.
-- 워커는 이 값만 보고 동작하므로 user access token을 요구하지 않고, 덕분에 세션 한정 토큰과
-- 장시간 분석이 양립한다.
CREATE TABLE analysis_runs
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT       NOT NULL,
    requested_by          BIGINT       NOT NULL,
    status                VARCHAR(30)  NOT NULL,
    installation_snapshot JSONB        NOT NULL,
    claimed_by            VARCHAR(100),
    claimed_at            TIMESTAMPTZ,
    attempts              INT          NOT NULL DEFAULT 0,
    -- 표시용이다. Phase 1은 이 시각에 자동으로 재개하지 않고 사용자가 다시 누른다.
    rate_limit_resume_at  TIMESTAMPTZ,
    error_code            VARCHAR(50),
    error_message         TEXT,
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT fk_analysis_runs_project FOREIGN KEY (project_id) REFERENCES projects (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_analysis_runs_user FOREIGN KEY (requested_by) REFERENCES users (id),
    CONSTRAINT ck_analysis_runs_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'RATE_LIMITED', 'PARTIALLY_COMPLETED',
                          'COMPLETED', 'FAILED', 'CANCELLED'))
);

-- 워커의 선점 쿼리가 이 인덱스를 탄다.
CREATE INDEX idx_analysis_runs_status_claimed_at ON analysis_runs (status, claimed_at);
CREATE INDEX idx_analysis_runs_project_created_at ON analysis_runs (project_id, created_at DESC);

-- 저장소 단위 부분 실패가 여기 기록된다. 하나가 FAILED여도 나머지는 계속 진행하고 전체는
-- PARTIALLY_COMPLETED가 된다.
--
-- 제외된 파일 "목록"은 저장하지 않는다. 개수와 사유 요약만 남긴다 — node_modules 하나만 있어도
-- 수만 행이 되고, 그 목록이 분석 결과에 주는 값은 개수와 사유 이상이 아니다.
CREATE TABLE analysis_run_repositories
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_run_id      BIGINT      NOT NULL,
    repository_id        BIGINT      NOT NULL,
    installation_id      BIGINT      NOT NULL,
    status               VARCHAR(20) NOT NULL,
    analyzed_commit_sha  VARCHAR(40),
    collected_file_count INT         NOT NULL DEFAULT 0,
    collected_bytes      BIGINT      NOT NULL DEFAULT 0,
    excluded_file_count  INT         NOT NULL DEFAULT 0,
    pr_collected_count   INT         NOT NULL DEFAULT 0,
    data_completeness    VARCHAR(20) NOT NULL DEFAULT 'COMPLETE',
    incomplete_reasons   JSONB,
    error_code           VARCHAR(50),
    error_message        TEXT,
    started_at           TIMESTAMPTZ,
    finished_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT fk_analysis_run_repositories_run
        FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs (id) ON DELETE CASCADE,
    -- 저장소를 프로젝트에서 빼면 그 저장소의 수집 근거도 함께 사라진다. 연결이 끊긴 저장소의
    -- 분석 이력만 남겨 둘 방법이 없고, 1B의 연결 해제를 FK 위반으로 막는 것도 답이 아니다.
    CONSTRAINT fk_analysis_run_repositories_repository
        FOREIGN KEY (repository_id) REFERENCES repositories (id) ON DELETE CASCADE,
    CONSTRAINT uk_analysis_run_repositories_run_repository
        UNIQUE (analysis_run_id, repository_id),
    CONSTRAINT ck_analysis_run_repositories_status
        CHECK (status IN ('PENDING', 'COLLECTING', 'COMPLETED', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_analysis_run_repositories_data_completeness
        CHECK (data_completeness IN ('COMPLETE', 'PARTIAL'))
);
